[package]
name = "collection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collection-macro = { path = "./collection-macro" }
mongodb = "2.3"

[dev-dependencies]
serde = "1"
